### ISSUE TITLE
Bug 🐛: Replace the zeros in the inputs with placeholders

### ISSUE THREAD

**Issue by YassinEldeeb** [Yassinmaher/tip-calculator#3]
Those should be placeholders and not initial values so that when someone types the values he doesn't need to first delete the zero.

And if you want the placeholder color to be vivit, [Check this out](https://www.w3schools.com/howto/howto_css_placeholder.asp) 

![IMG_20220102_164739](https://user-images.githubusercontent.com/72823042/147879546-323292c6-e11a-44ba-902f-31916256f56a.jpg)

**Comment by Yassinmaher** [comment]
Thank You 
Please Check The Updated Version
