### ISSUE TITLE
Bug 🐛: Tip Calculator doesn't actually calculate any values based on my input

### ISSUE THREAD

**Issue by YassinEldeeb** [Yassinmaher/tip-calculator#4]
`Tip Amount/Person` & `Total/Person` should be calculated based on my input values so that It's actually a functional app.

You can plugin this formula very easily to do so:

```js
TipPerPerson = (Bill * percentage) / NumOfPersons

TotalTip = Bill * percentage
```

**Comment by Yassinmaher** [comment]
Oh Sorry for that
Check the update version
